### ISSUE TITLE
Implementar corte de caja

### ISSUE THREAD

**Issue by mgallegos** [mgallegos/decima-pos#165]
**Paso 1:** Ejecutar script
```
USE `decima_pos`;

ALTER TABLE `inv_discount` 
ADD COLUMN `position` TINYINT(1) NULL DEFAULT '0' AFTER `value`;

ALTER TABLE `purch_tax` 
ADD COLUMN `position` TINYINT(1) NULL DEFAULT '0' AFTER `proof_concept`;

ALTER TABLE `purch_document_type` 
ADD COLUMN `position` TINYINT(1) NULL DEFAULT '0' AFTER `has_decrease_effect`;

ALTER TABLE `purch_payment_term` 
ADD COLUMN `position` TINYINT(1) NULL DEFAULT '0' AFTER `value`;

ALTER TABLE `purch_payment_term` 
ADD COLUMN `payment_form_cloud_id` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `position`;

ALTER TABLE `sale_order` 
ADD COLUMN `cash_closing_detail_id` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `client_local_id`;

CREATE TABLE `POS_Cash_Closing` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `number` int(11) DEFAULT NULL,
  `date` date DEFAULT NULL,
  `total_amount` double(13,2) NOT NULL DEFAULT '0.00',
  `created_by` int(10) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pos_cash_created_by_index` (`created_by`),
  KEY `pos_cash_closing_date_index` (`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `POS_Cash_Closing_Detail` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `amount` double(13,2) NOT NULL DEFAULT '0.00',
  `payment_term_id` int(10) unsigned NOT NULL,
  `cash_closing_id` int(10) unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `pos_cash_closing_detail_payment_term_id_index` (`payment_term_id`),
  KEY `pos_cash_closing_detail_cash_closing_id_index` (`cash_closing_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ekars
UPDATE `purch_payment_term` SET `payment_form_cloud_id`='1' WHERE `id`='1';
```
**Paso 2:** Modificar la asignación del paymentFormId en el insert de la venta, en esta asignación se debe utilizar el nuevo campo "payment_form_cloud_id" de la condición de pago seleccionado.

**Paso 3:** Mostrar condiciones de pago, tipos de documento, impuestos y descuento ordenados por el nuevo campo "position"

**Paso 4:** Agregar menú "Corte de caja" en menú desplegable

**Paso 5:** La pantalla corte de caja es un maestro - detalle con estas características:
- Mostrar toolbar con estos botones: Actualizar, Nuevo, Anular, Regresar
- En la primera tabla mostrar solo lo últimos 5 registros con estos campos: Correlativo, Fecha, Creado por, Creado el (created_at), Total
- Al dar click en la primera tabla, mostrar en una segunda tabla los registros asociados al maestro (a través de la columna "cash_closing_id") con estos campos: Condición de pago y Monto
- Al dar click en nuevo, mostrar una popup con titulo "Nuevo corte de caja" que solo tenga el campo fecha (por defecto la fecha actual, pero que sea editable) y abajo un botón: Guardar.
- Al dar click en guardar, guardar registro en la tabla POS_Cash_Closing (en el campo created_at guardar la fecha y hora de la operación), luego iterar todas las ventas (SALE_Order) con la fecha seleccionada y que tenga NULL en el campo cash_closing_detail_id y agruparlas por payment_term_id (sumar los montos) y guardar registros agrupados en tabla POS_Cash_Closing_Detail, por último una vez creado el registro en POS_Cash_Closing_Detail en cada venta que se tomo para ese registro hace un update en el campo cash_closing_detail_id de SALE_Order.
**Paso 6:** Hacer UPDATE en el campo total_amount del registro POS_Cash_Closing con el total de todas las condiciones de pago.
**Paso 7:** Incluir el corte de caja en la sincronización

**Comment by AlejandroJuarez97** [comment]
- Campo: Positon.
Descripción: Representa el orden en el cual se muestran los resultados de la base de datos, se emplea   como método de ordenamiento.

- Campo: payment_form_cloud_id.
Descripción: Campo asociado a los términos de pago. Eliminar forma de pago estática del archivo de configuración.
Ejemplo: Contado -> Cheque, efectivo.
